apiVersion: v1
kind: Service
metadata:
    name: "myakscluster002-6e00"
    labels:
        app: "myakscluster002-6e00"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myakscluster002-6e00"